name: isar_test
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  bloc: ^8.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5

dev_dependencies:
  build_runner: ^2.3.2
  flutter_test:
    sdk: flutter
  isar_generator: ^3.0.5
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
